#!/bin/bash

set -e

destination_accounts=`shuf /usr/share/dict/words | rg -v "'" | head -4`
input=$(echo $destination_accounts | tr ' ' ',')
curl -k -s http://jobcoin.gemini.com/phosphate/create -H 'Content-Type: application/json' -d "{\"address\": \"test-deposit\"}"

(echo $input; sleep 20) | sbt run
for acc in $destination_accounts; do
    echo $acc
    curl -k -s http://jobcoin.gemini.com/phosphate/api/addresses/$acc | jq
done

echo "Emptying test deposit addr and pool..."
for acc in test-deposit test-pool; do
    balance=$(curl -k -s http://jobcoin.gemini.com/phosphate/api/addresses/$acc | jq .balance)
    transfer_body="{ \"fromAddress\": \"$acc\", \"toAddress\": \"void\", \"amount\" : $balance }"
    curl -k -s http://jobcoin.gemini.com/phosphate/api/transactions -H 'Content-Type: application/json' --data "$transfer_body" | jq
done

